### PR TITLE
Release v2.1.0

### PR DESCRIPTION
**Pull request by kael-shipman**
* [x] Add flat file reader (#18)
* [x] Add `default` property to field spec to allow for optional fields (with defaults) (#16)
* [x] Add `enum` field type (#26)
* [x] Add `description` to common field spec (#29)

(formerly #25)

### CODE REVIEW

**Comment by kael-shipman** [comment]
Think I may have messed up our commit history a bit here. I merged master into my feature branch not realizing that you had done squash commits, so now the same commits are being re-applied. I'd say let's not worry about it, though, since when we squash it again, we'll clean up the history at the point. Sorry bout that.

**Comment by kael-shipman** [comment]
I just added the 'dataToLines' function because I'm using this library in an environment where I'm not actually writing the file locally (I'm writing it to an SFTP writable stream). The function simple uses `rowFormatter` to format rows of data and returns them as an array of lines.

**Comment by kael-shipman** [comment]
Also, I just removed #17 from this release because it's too much work for too little gain right now. Given that, I'm ready to release this whenever you are. If you see anything that you don't like, please let me know so we can talk about it.

**Comment by kael-shipman** [comment]
@cimasim89 poke! Any thoughts here?

**Comment by cimasim89** [comment]
Sorry Kael for my late I will check as soon as possible.

**Review by cimasim89 — APPROVED** [review]

**Comment by cimasim89** [comment]
I think these new features can be merged if you approve. Only, about this:

> Think I may have messed up our commit history a bit here. I merged master into my feature branch not realizing that you had done squash commits, so now the same commits are being re-applied. I'd say let's not worry about it, though, since when we squash it again, we'll clean up the history at the point. Sorry bout that.

it's okay, I tend to use rebase instead of merge, but I don't think we'll have a problem with that. You can check what append using `git pull --rebase origin develop`  if you want to try to have a more clean history before merge.

**Comment by kael-shipman** [comment]
Sorry, I had to slip in a last-minute fix here in commit a69f268. I discovered that using an index type for `RowData` was problematic because in certain cases if you try to pass a defined type into it, it fails because the defined type cannot accept fields that are not already defined (i.e., the defined type is not an index type, which accepts arbitrary fields). For example:

```
type Person = {
  name: string;
  birthday: Date;
}

const me: Person = {
  name: "Jim Chavo",
  birthday: new Date("1999-01-01T08:36:00-0500"),
}

const rowdata: RowData = me; // << Error
```

Interestingly, the above example doesn't actually produce an error, but I was fighting with a real-world scenario that actually did produce an error, and I don't have time to fully debug and understand why, so this is the best I've got.

Anyway, I changed `RowData` to accept a type parameter, `T`, and then just enforced that each field in T has a value that's compatible with `FieldValue`.

I'm going to go ahead and squash-merge this now, which should put us a in a position to merge into `master` and officially release v2.1.0. Lemme know if you'd like me to do that if you'd prefer to.

**Comment by kael-shipman** [comment]
Ok, closing this PR and branch in order to open another with cleaner history.

**Pull request closed without merging**
