### PR TITLE
WIP: Release v2.1.0

### PR DESCRIPTION
**Pull request by kael-shipman**
* [x] Add flat file reader (#18)
* [x] Add `default` property to field spec to allow for optional fields (with defaults) (#16)
* [ ] Add `boolean` field type (#17)
* [ ] Add `enum` field type (#26)
* [ ] Add `description` to common field spec (#29)

### CODE REVIEW

**Comment by kael-shipman** [comment]
Hm... Just looked at the failed linting and I feel like some of what it's complaining about are some of the things I value most about Typescript. It doesn't like `public` accessibility modifiers, but I find the consistency in having modifiers on all class methods very valuable, especially for, e.g., searching for all public class methods.

It also doesn't like what it considers "trivially inferred" typescript types, but again, I find it easier to step into codebases when types are clearly annotated.

Would you be amenable to tweaking those settings a bit to eliminate some of the stylistic grievances?

**Comment by cimasim89** [comment]
Biao Kael, there's no problem for me if we want to take down rules that aren't useful.

**Comment by kael-shipman** [comment]
Ok, cool. I actually don't know how to adjust these rules. Is this something you've given me permission to do? Is it here in Github? Or in CircleCI or somewhere like that?

I'm starting to incorporate this into my implementation at work now, so I'd like to get to a place where we can publish a release of it that I can depend on.

**Comment by kael-shipman** [comment]
Found it! And fixed it according to my stylistic opinions. If you want to be more strict about style, you can undo some of that last commit, but most of that stuff I use intentionally for better readability.

Ok, I think this is ready to go. Please approve/request changes when you get a chance.

**Comment by kael-shipman** [comment]
Changing this PR to encompass all remaining outstanding issues, since there's way too much overhead to making a separate PR for each.

**Comment by kael-shipman** [comment]
Closing this out because I changed the name of the underlying branch to reflect the new broader scope of the PR.

**Pull request closed without merging**
